-- MySQL Script generated by MySQL Workbench
-- Mon Apr  1 22:02:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema saf
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema saf
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `saf` DEFAULT CHARACTER SET utf8 ;
USE `saf` ;

-- -----------------------------------------------------
-- Table `saf`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saf`.`setor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `setor` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `saf`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `saf`.`funcionario` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(99) NULL,
  `bloqueado` ENUM('S', 'N') NULL,
  `id_setor` INT NOT NULL,
  PRIMARY KEY (`matricula`, `id_setor`),
  INDEX `fk_funcionario_setor_idx` (`id_setor` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_setor`
    FOREIGN KEY (`id_setor`)
    REFERENCES `saf`.`setor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
