name: crud
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.3.0

dependencies:
  # path: ^1.8.0
  http: ^1.2.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
